In [1]:
!pwd

/Users/jdm/Workbench/Perlan/data_convert

In [87]:
import os
import pandas as pd
import path_utils as pu

In [88]:
root = ".."
os.chdir(root)
svn_root  = 'Controlled.svn/Systems/Data Network Logs/'
data_root = 'data/'
flights_root = data_root + 'Flights'
ballons_root = data_root + 'Soundings'

In [89]:
csv = pd.read_csv(f"{data_root}/flights.csv")
csv['data_ac'] = None
csv['data_uv'] = None
csv['data_kml'] = None

In [90]:
csv.head()

,Unnamed: 0,flight_number,flight_date,city,airport,takeoff_time_local,landing_time_local,duration,release_altitude_feet,maximum_altitude_feet,maximum_gps_altitude_feet,significance,pic,sic,data_ac,data_uv,data_kml
0,0,1.0,2015-09-23,"Redmond, OR",KRDM,818.0,851.0,0.6,8100.0,8100.0,NaN,First Flight,Jim Payne,Morgan Sandercock,None,None,None
1,1,2.0,2016-01-15,"Minden, NV",KMEV,1307.0,1350.0,0.7,10800.0,10800.0,NaN,flight testing,Jim Payne,Miguel Iturmendi,None,None,None
2,2,3.0,2016-01-15,"Minden, NV",KMEV,1420.0,1502.0,0.7,10700.0,10700.0,NaN,NaN,Jim Payne,Miguel Iturmendi,None,None,None
3,3,4.0,2016-01-27,"Minden, NV",KMEV,1423.0,1445.0,0.4,7600.0,7600.0,NaN,NaN,Jim Payne,NaN,None,None,None
4,4,5.0,2016-01-27,"Minden, NV",KMEV,1525.0,1555.0,0.5,8700.0,8700.0,NaN,NaN,Jim Payne,NaN,None,None,None

In [99]:
rec = csv[csv['flight_number'] == 65]
rec.values

array([[64, 65.0, '2019-09-17', 'El Calafate', 'SAWC', 1120.0, 1650.0,
        5.5, 51000.0, 65000.0, nan, 'Last flight of 2019', 'Jim Payne',
        'Morgan Sandercock',
        'http://localhost/data/Flights/0065/Flt0065AC.xlsx',
        'http://localhost/data/Flights/0065/Flt0065UV.xlsx',
        'http://localhost/data/Flights/0065/Flt0065.kml']], dtype=object)

In [94]:
flts = pu.get_subdirs(flights_root)

#flts

In [95]:
def stuff_file_paths(df=None, flight_dirs=None, host="http://localhost", verbose=1):
    for flt in flight_dirs:
        files_full = pu.get_files(flt)
        files = [f[f.rfind('/')+1:] for f in files_full]
        if files == []:
            continue
        
        nr = int(flt[-4:])
        if verbose:
            print(f"#{nr}\t{flt}\t{files}")

        for file in files_full:
            file = f'{host}/{file}'
            base = file[:file.rfind('.')]
            suffix = file[file.rfind('.')+1:]
            idx = nr - 1
            #if verbose:
            #    print(f"base = {base}   suffix = {suffix}")
            if suffix == 'kml':
                df.loc[idx, 'data_kml'] = file
                if verbose:
                    print(f"KML = {file}")
            #print(f"base[-2:]={base[-2:]}")
            if base[-2:] == 'AC':
                df.loc[idx, 'data_ac'] = file
                if verbose:
                    print(f"AC = {file}")
            if base[-2:] == 'UV':
                df.loc[idx, 'data_uv'] = file
                if verbose:
                    print(f"UV = {file}")
    return df

df2 = stuff_file_paths(df=csv, flight_dirs=flts)
df2

#61	data/Flights/0061	['Flt0061AC.xlsb', 'Flt0061.kml', 'Flt0061UV.xlsx']
AC = http://localhost/data/Flights/0061/Flt0061AC.xlsb
KML = http://localhost/data/Flights/0061/Flt0061.kml
UV = http://localhost/data/Flights/0061/Flt0061UV.xlsx
#59	data/Flights/0059	['Flt0059AC.xlsx', 'Flt0059.kml', 'Flt0059UV.xlsx']
AC = http://localhost/data/Flights/0059/Flt0059AC.xlsx
KML = http://localhost/data/Flights/0059/Flt0059.kml
UV = http://localhost/data/Flights/0059/Flt0059UV.xlsx
#50	data/Flights/0050	['Flt0050UV.xlsx', 'Flt0050.kml', 'Flt0050AC.xlsb']
UV = http://localhost/data/Flights/0050/Flt0050UV.xlsx
KML = http://localhost/data/Flights/0050/Flt0050.kml
AC = http://localhost/data/Flights/0050/Flt0050AC.xlsb
#57	data/Flights/0057	['Flt0057AC.xlsx', 'Flt0057UV.xlsx']
AC = http://localhost/data/Flights/0057/Flt0057AC.xlsx
UV = http://localhost/data/Flights/0057/Flt0057UV.xlsx
#32	data/Flights/0032	['Flt0032AC.xlsb', 'Flt0032.kml']
AC = http://localhost/data/Flights/0032/Flt0032AC.xlsb
KML = http://localhost/data/Flights/0032/Flt0032.kml
#35	data/Flights/0035	['Flt0035AC.xlsb', 'Flt0035.kml']
AC = http://localhost/data/Flights/0035/Flt0035AC.xlsb
KML = http://localhost/data/Flights/0035/Flt0035.kml
#51	data/Flights/0051	['Flt0051AC.xlsb', 'Flt0051.kml', 'Flt0051UV.xlsx']
AC = http://localhost/data/Flights/0051/Flt0051AC.xlsb
KML = http://localhost/data/Flights/0051/Flt0051.kml
UV = http://localhost/data/Flights/0051/Flt0051UV.xlsx
#58	data/Flights/0058	['.DS_Store', 'Flt0058UV.xlsx', 'Flt0058AC.xlsx']
UV = http://localhost/data/Flights/0058/Flt0058UV.xlsx
AC = http://localhost/data/Flights/0058/Flt0058AC.xlsx
#60	data/Flights/0060	['Flt0060UV.xlsx', 'Flt0060AC.xlsb']
UV = http://localhost/data/Flights/0060/Flt0060UV.xlsx
AC = http://localhost/data/Flights/0060/Flt0060AC.xlsb
#34	data/Flights/0034	['Flt0034AC.xlsb']
AC = http://localhost/data/Flights/0034/Flt0034AC.xlsb
#33	data/Flights/0033	['Flt0033.kml', 'Flt0033AC.xlsb']
KML = http://localhost/data/Flights/0033/Flt0033.kml
AC = http://localhost/data/Flights/0033/Flt0033AC.xlsb
#20	data/Flights/0020	['Flt0020AC.xlsx']
AC = http://localhost/data/Flights/0020/Flt0020AC.xlsx
#29	data/Flights/0029	['Flt0029AC.xlsx']
AC = http://localhost/data/Flights/0029/Flt0029AC.xlsx
#42	data/Flights/0042	['.DS_Store', 'Flt0042UV.xlsx', 'Flt0042AC.xlsx']
UV = http://localhost/data/Flights/0042/Flt0042UV.xlsx
AC = http://localhost/data/Flights/0042/Flt0042AC.xlsx
#45	data/Flights/0045	['Flt0045AC.xlsx', 'Flt0045.kml']
AC = http://localhost/data/Flights/0045/Flt0045AC.xlsx
KML = http://localhost/data/Flights/0045/Flt0045.kml
#28	data/Flights/0028	['Flt0028AC.xlsx']
AC = http://localhost/data/Flights/0028/Flt0028AC.xlsx
#19	data/Flights/0019	['Flt0019AC.xlsx']
AC = http://localhost/data/Flights/0019/Flt0019AC.xlsx
#26	data/Flights/0026	['Flt0025AC.xlsx', 'Flt0026.kml']
AC = http://localhost/data/Flights/0026/Flt0025AC.xlsx
KML = http://localhost/data/Flights/0026/Flt0026.kml
#21	data/Flights/0021	['Flt0021.kml', 'Flt0021AC.xlsx']
KML = http://localhost/data/Flights/0021/Flt0021.kml
AC = http://localhost/data/Flights/0021/Flt0021AC.xlsx
#38	data/Flights/0038	['Flt0038AC.xlsb', 'Flt0038.kml']
AC = http://localhost/data/Flights/0038/Flt0038AC.xlsb
KML = http://localhost/data/Flights/0038/Flt0038.kml
#36	data/Flights/0036	['Flt0036AC.xlsb', 'Flt0036.kml']
AC = http://localhost/data/Flights/0036/Flt0036AC.xlsb
KML = http://localhost/data/Flights/0036/Flt0036.kml
#31	data/Flights/0031	['Flt0031AC.xlsx', 'Flt0031.kml']
AC = http://localhost/data/Flights/0031/Flt0031AC.xlsx
KML = http://localhost/data/Flights/0031/Flt0031.kml
#65	data/Flights/0065	['Flt0065AC.xlsx', 'Flt0065.kml', 'Flt0065UV.xlsx']
AC = http://localhost/data/Flights/0065/Flt0065AC.xlsx
KML = http://localhost/data/Flights/0065/Flt0065.kml
UV = http://localhost/data/Flights/0065/Flt0065UV.xlsx
#62	data/Flights/0062	['Flt0062UV.xlsx', 'Flt0062.kml', 'Flt0062AC.xlsb']
UV = http://localhost/data/Flights/0062/Flt0062UV.xlsx
KML = http://localhost/data/Flights/0062/Flt0062.kml
AC = http://localhost/data/Flights/0062/Flt0062AC.xlsb
#54	data/Flights/0054	['Flt0054AC.xlsb', 'Flt0054.kml']
AC = http://localhost/data/Flights/0054/Flt0054AC.xlsb
KML = http://localhost/data/Flights/0054/Flt0054.kml
#53	data/Flights/0053	['Flt0053AC.xlsb', 'Flt0053.kml', 'Flt0053UV.xlsx']
AC = http://localhost/data/Flights/0053/Flt0053AC.xlsb
KML = http://localhost/data/Flights/0053/Flt0053.kml
UV = http://localhost/data/Flights/0053/Flt0053UV.xlsx
#30	data/Flights/0030	['Flt0030AC.xlsx']
AC = http://localhost/data/Flights/0030/Flt0030AC.xlsx
#37	data/Flights/0037	['Flt0037AC.xlsx', 'Flt0037.kml']
AC = http://localhost/data/Flights/0037/Flt0037AC.xlsx
KML = http://localhost/data/Flights/0037/Flt0037.kml
#39	data/Flights/0039	['Flt0039.kml', 'Flt0039AC.xlsx']
KML = http://localhost/data/Flights/0039/Flt0039.kml
AC = http://localhost/data/Flights/0039/Flt0039AC.xlsx
#52	data/Flights/0052	['Flt0052UV.xlsx', 'Flt0052.kml', 'Flt0052AC.xlsb']
UV = http://localhost/data/Flights/0052/Flt0052UV.xlsx
KML = http://localhost/data/Flights/0052/Flt0052.kml
AC = http://localhost/data/Flights/0052/Flt0052AC.xlsb
#55	data/Flights/0055	['Flt0055AC.xlsx', 'Flt0055UV.xlsx']
AC = http://localhost/data/Flights/0055/Flt0055AC.xlsx
UV = http://localhost/data/Flights/0055/Flt0055UV.xlsx
#63	data/Flights/0063	['Flt0063AC.xlsb', 'Flt0063.kml', 'Flt0063UV.xlsb']
AC = http://localhost/data/Flights/0063/Flt0063AC.xlsb
KML = http://localhost/data/Flights/0063/Flt0063.kml
UV = http://localhost/data/Flights/0063/Flt0063UV.xlsb
#64	data/Flights/0064	['Flt0064.kml', 'Flt0064UV.xlsb', 'Flt0064AC.xlsb']
KML = http://localhost/data/Flights/0064/Flt0064.kml
UV = http://localhost/data/Flights/0064/Flt0064UV.xlsb
AC = http://localhost/data/Flights/0064/Flt0064AC.xlsb
#46	data/Flights/0046	['.DS_Store', 'Flt0046UV.xlsx', 'Flt0046AC.xlsx', 'Flt0046.kml']
UV = http://localhost/data/Flights/0046/Flt0046UV.xlsx
AC = http://localhost/data/Flights/0046/Flt0046AC.xlsx
KML = http://localhost/data/Flights/0046/Flt0046.kml
#41	data/Flights/0041	['Flt0041AC.xlsx', 'Flt0041UV.xlsx']
AC = http://localhost/data/Flights/0041/Flt0041AC.xlsx
UV = http://localhost/data/Flights/0041/Flt0041UV.xlsx
#48	data/Flights/0048	['Flt0048UV.xlsx', 'Flt0048.kml', 'Flt0048AC.xlsb']
UV = http://localhost/data/Flights/0048/Flt0048UV.xlsx
KML = http://localhost/data/Flights/0048/Flt0048.kml
AC = http://localhost/data/Flights/0048/Flt0048AC.xlsb
#24	data/Flights/0024	['Flt0024AC.xlsx']
AC = http://localhost/data/Flights/0024/Flt0024AC.xlsx
#23	data/Flights/0023	['Flt0023.kml', 'Flt0023AC.xlsx']
KML = http://localhost/data/Flights/0023/Flt0023.kml
AC = http://localhost/data/Flights/0023/Flt0023AC.xlsx
#49	data/Flights/0049	['.DS_Store', 'Flt0049AC.xlsb', 'Flt0049.kml', 'Flt0049UV.xlsx']
AC = http://localhost/data/Flights/0049/Flt0049AC.xlsb
KML = http://localhost/data/Flights/0049/Flt0049.kml
UV = http://localhost/data/Flights/0049/Flt0049UV.xlsx
#40	data/Flights/0040	['Flt0040.kml', 'Flt0040AC.xlsx']
KML = http://localhost/data/Flights/0040/Flt0040.kml
AC = http://localhost/data/Flights/0040/Flt0040AC.xlsx
#47	data/Flights/0047	['Flt0047AC.xlsb', '.DS_Store', 'Flt0047UV.xlsx']
AC = http://localhost/data/Flights/0047/Flt0047AC.xlsb
UV = http://localhost/data/Flights/0047/Flt0047UV.xlsx
#22	data/Flights/0022	['Flt0022AC.xlsx', 'Flt0022.kml']
AC = http://localhost/data/Flights/0022/Flt0022AC.xlsx
KML = http://localhost/data/Flights/0022/Flt0022.kml
#25	data/Flights/0025	['Flt0025AC.xlsx', 'Flt0025.kml']
AC = http://localhost/data/Flights/0025/Flt0025AC.xlsx
KML = http://localhost/data/Flights/0025/Flt0025.kml

,Unnamed: 0,flight_number,flight_date,city,airport,takeoff_time_local,landing_time_local,duration,release_altitude_feet,maximum_altitude_feet,maximum_gps_altitude_feet,significance,pic,sic,data_ac,data_uv,data_kml
0,0,1.0,2015-09-23,"Redmond, OR",KRDM,818.0,851.0,0.6,8100.0,8100.0,NaN,First Flight,Jim Payne,Morgan Sandercock,None,None,None
1,1,2.0,2016-01-15,"Minden, NV",KMEV,1307.0,1350.0,0.7,10800.0,10800.0,NaN,flight testing,Jim Payne,Miguel Iturmendi,None,None,None
2,2,3.0,2016-01-15,"Minden, NV",KMEV,1420.0,1502.0,0.7,10700.0,10700.0,NaN,NaN,Jim Payne,Miguel Iturmendi,None,None,None
3,3,4.0,2016-01-27,"Minden, NV",KMEV,1423.0,1445.0,0.4,7600.0,7600.0,NaN,NaN,Jim Payne,NaN,None,None,None
4,4,5.0,2016-01-27,"Minden, NV",KMEV,1525.0,1555.0,0.5,8700.0,8700.0,NaN,NaN,Jim Payne,NaN,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,61,62.0,2019-09-06,El Calafate,SAWC,1333.0,1636.0,3.1,42000.0,42300.0,NaN,NaN,Jim Payne,Morgan Sandercock,http://localhost/data/Flights/0062/Flt0062AC.xlsb,http://localhost/data/Flights/0062/Flt0062UV.xlsx,http://localhost/data/Flights/0062/Flt0062.kml
62,62,63.0,2019-09-11,El Calafate,SAWC,1235.0,1811.0,5.6,47100.0,50600.0,NaN,tow height record,Jim Payne,Tim Gardner,http://localhost/data/Flights/0063/Flt0063AC.xlsb,http://localhost/data/Flights/0063/Flt0063UV.xlsb,http://localhost/data/Flights/0063/Flt0063.kml
63,63,64.0,2019-09-14,El Calafate,SAWC,913.0,1230.0,3.3,45100.0,49200.0,NaN,NaN,Jim Payne,Miguel Iturmendi,http://localhost/data/Flights/0064/Flt0064AC.xlsb,http://localhost/data/Flights/0064/Flt0064UV.xlsb,http://localhost/data/Flights/0064/Flt0064.kml
64,64,65.0,2019-09-17,El Calafate,SAWC,1120.0,1650.0,5.5,51000.0,65000.0,NaN,Last flight of 2019,Jim Payne,Morgan Sandercock,http://localhost/data/Flights/0065/Flt0065AC.xlsx,http://localhost/data/Flights/0065/Flt0065UV.xlsx,http://localhost/data/Flights/0065/Flt0065.kml
65,65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None

In [96]:
len(csv[csv['data_kml'].notnull()])

29

In [97]:
csv[ csv['data_kml'].notnull()][['data_kml', 'data_ac', 'data_uv']]

,data_kml,data_ac,data_uv
20,http://localhost/data/Flights/0021/Flt0021.kml,http://localhost/data/Flights/0021/Flt0021AC.xlsx,None
21,http://localhost/data/Flights/0022/Flt0022.kml,http://localhost/data/Flights/0022/Flt0022AC.xlsx,None
22,http://localhost/data/Flights/0023/Flt0023.kml,http://localhost/data/Flights/0023/Flt0023AC.xlsx,None
24,http://localhost/data/Flights/0025/Flt0025.kml,http://localhost/data/Flights/0025/Flt0025AC.xlsx,None
25,http://localhost/data/Flights/0026/Flt0026.kml,http://localhost/data/Flights/0026/Flt0025AC.xlsx,None
30,http://localhost/data/Flights/0031/Flt0031.kml,http://localhost/data/Flights/0031/Flt0031AC.xlsx,None
31,http://localhost/data/Flights/0032/Flt0032.kml,http://localhost/data/Flights/0032/Flt0032AC.xlsb,None
32,http://localhost/data/Flights/0033/Flt0033.kml,http://localhost/data/Flights/0033/Flt0033AC.xlsb,None
34,http://localhost/data/Flights/0035/Flt0035.kml,http://localhost/data/Flights/0035/Flt0035AC.xlsb,None
35,http://localhost/data/Flights/0036/Flt0036.kml,http://localhost/data/Flights/0036/Flt0036AC.xlsb,None
36,http://localhost/data/Flights/0037/Flt0037.kml,http://localhost/data/Flights/0037/Flt0037AC.xlsx,None
37,http://localhost/data/Flights/0038/Flt0038.kml,http://localhost/data/Flights/0038/Flt0038AC.xlsb,None
38,http://localhost/data/Flights/0039/Flt0039.kml,http://localhost/data/Flights/0039/Flt0039AC.xlsx,None
39,http://localhost/data/Flights/0040/Flt0040.kml,http://localhost/data/Flights/0040/Flt0040AC.xlsx,None
44,http://localhost/data/Flights/0045/Flt0045.kml,http://localhost/data/Flights/0045/Flt0045AC.xlsx,None
45,http://localhost/data/Flights/0046/Flt0046.kml,http://localhost/data/Flights/0046/Flt0046AC.xlsx,http://localhost/data/Flights/0046/Flt0046UV.xlsx
47,http://localhost/data/Flights/0048/Flt0048.kml,http://localhost/data/Flights/0048/Flt0048AC.xlsb,http://localhost/data/Flights/0048/Flt0048UV.xlsx
48,http://localhost/data/Flights/0049/Flt0049.kml,http://localhost/data/Flights/0049/Flt0049AC.xlsb,http://localhost/data/Flights/0049/Flt0049UV.xlsx
49,http://localhost/data/Flights/0050/Flt0050.kml,http://localhost/data/Flights/0050/Flt0050AC.xlsb,http://localhost/data/Flights/0050/Flt0050UV.xlsx
50,http://localhost/data/Flights/0051/Flt0051.kml,http://localhost/data/Flights/0051/Flt0051AC.xlsb,http://localhost/data/Flights/0051/Flt0051UV.xlsx
51,http://localhost/data/Flights/0052/Flt0052.kml,http://localhost/data/Flights/0052/Flt0052AC.xlsb,http://localhost/data/Flights/0052/Flt0052UV.xlsx
52,http://localhost/data/Flights/0053/Flt0053.kml,http://localhost/data/Flights/0053/Flt0053AC.xlsb,http://localhost/data/Flights/0053/Flt0053UV.xlsx
53,http://localhost/data/Flights/0054/Flt0054.kml,http://localhost/data/Flights/0054/Flt0054AC.xlsb,None
58,http://localhost/data/Flights/0059/Flt0059.kml,http://localhost/data/Flights/0059/Flt0059AC.xlsx,http://localhost/data/Flights/0059/Flt0059UV.xlsx
60,http://localhost/data/Flights/0061/Flt0061.kml,http://localhost/data/Flights/0061/Flt0061AC.xlsb,http://localhost/data/Flights/0061/Flt0061UV.xlsx
61,http://localhost/data/Flights/0062/Flt0062.kml,http://localhost/data/Flights/0062/Flt0062AC.xlsb,http://localhost/data/Flights/0062/Flt0062UV.xlsx
62,http://localhost/data/Flights/0063/Flt0063.kml,http://localhost/data/Flights/0063/Flt0063AC.xlsb,http://localhost/data/Flights/0063/Flt0063UV.xlsb
63,http://localhost/data/Flights/0064/Flt0064.kml,http://localhost/data/Flights/0064/Flt0064AC.xlsb,http://localhost/data/Flights/0064/Flt0064UV.xlsb
64,http://localhost/data/Flights/0065/Flt0065.kml,http://localhost/data/Flights/0065/Flt0065AC.xlsx,http://localhost/data/Flights/0065/Flt0065UV.xlsx

In [98]:
csv.to_csv(f"{data_root}/flights.csv")

In [ ]:
# Copy files from SVN

In [18]:
import path_utils as pu

svn_flights = pu.get_svn_flight_dirs(svn_root)

def reverse_dict(dic):
    return {dic[key]:key for key in dic}

svn_flights_reverse = reverse_dict(svn_flights)

In [19]:
kmls = pu.get_children(svn_root, kind="files", names_ending_with=".kml", depth=4)
kmls

['Flt53 10 Sept 2018/Screenshots/Perlan2.kml',
 'Flt33 03 August 2017/Perlan2.kml',
 'Gnd Hatch Test 9 Aug 2018/Perlan2.kml',
 'Flt22 Sept 18/Flight22.kml',
 'Flt21 13 Sept 2016/Flight21.kml',
 'Flt39 9 Sept 2017/Perlan2.kml',
 'Flt25 25 Sept 2016/Flight25.kml',
 'Flt54 12 Sep 2018/Flt54.kml',
 'Flt32 31 July 2017/Perlan2.kml',
 'Flt45 26 May 2018/Perlan2.kml',
 'Flt36 24 Aug 2017/Perlan2.kml',
 'Flt47 13 Aug 2018/Perlan2.kml',
 'Flt63 11 Sept 2019/Flt63 Telemetry/Perlan2.kml',
 'Flt65 17 Sept 2019/Flt65 Telemetry/Perlan2.kml',
 'Flt40 11 Sept 2017/Perlan2.kml',
 'Flt52 2 Sep 2018/Flt52.kml',
 'Flt37 30 Aug 2017/Perlan2.kml',
 'Flt64 14 Sept 2019/Flt64 Telemetry/Perlan2.kml',
 'Flt50 26 Aug 2018/Perlan2.kml',
 'Flt23 21 Sept 2016/Flight23.kml',
 'Flt35 19 Aug 2017/Perlan2.kml',
 'Flt62 6 Sept 2019/Flt62 Telemetry/Perlan2.kml',
 'Flt31 24 July 2017/Perlan2.kml',
 'Flt49 20 Aug 2018/Perlan2.kml',
 'Flt61 31 Aug 2019/Flt61 Groundstation/Perlan2.kml',
 'Flt26 25 Sept 2016/Flight26.kml',
 'Flt38 3 Sept 2017/Perlan2.kml',
 'Flt48 17 Aug 2018/Ground Station Logs/Perlan2.kml',
 'Flt51 28 Aug 2018/Perlan2.kml',
 'Flt59 20 Aug 2019/Flt59 Telemetry/Perlan2.kml']

In [22]:
svn_flights = pu.get_svn_flight_dirs(svn_root)
svn_flights

{'0053': 'Flt53 10 Sept 2018',
 '0033': 'Flt33 03 August 2017',
 '0022': 'Flt22 Sept 18',
 '0021': 'Flt21 13 Sept 2016',
 '0042': 'Flt42',
 '0039': 'Flt39 9 Sept 2017',
 '0024': 'Flt24 23 Sept 2016',
 '0025': 'Flt25 25 Sept 2016',
 '0054': 'Flt54 12 Sep 2018',
 '0030': 'Flt30 18 July 2017',
 '0032': 'Flt32 31 July 2017',
 '0041': 'Flt41 06 May 2018',
 '0029': 'Flt29 12 May 2017',
 '0045': 'Flt45 26 May 2018',
 '0036': 'Flt36 24 Aug 2017',
 '0047': 'Flt47 Aug 14 2018',
 '0034': 'Flt34 15 Aug 2017',
 '0058': 'Flt58 3 Jun 2019',
 '0063': 'Flt63 11 Sept 2019',
 '0065': 'Flt65 17 Sept 2019',
 '0028': 'Flt28 22 April 2017',
 '0040': 'Flt40 11 Sept 2017',
 '0052': 'Flt52 2 Sep 2018',
 '0037': 'Flt37 30 Aug 2017',
 '0027': 'Flt27 11 April 2017',
 '0064': 'Flt64 14 Sept 2019',
 '0057': 'Flt57 1 Jun 2019',
 '0060': 'Flt60 28 Aug 2019',
 '0050': 'Flt50 26 Aug 2018',
 '0023': 'Flt23 21 Sept 2016',
 '0035': 'Flt35 19 Aug 2017',
 '0055': 'Flt55 28 May 2019',
 '0062': 'Flt62 6 Sept 2019',
 '0031': 'Flt31 24 July 2017',
 '0020': 'Flt20 11 Sept',
 '0056': 'Flt56 29 May 2019',
 '0049': 'Flt49 20 Aug 2018',
 '0061': 'Flt61 31 Aug 2019',
 '0026': 'Flt26 25 Sept 2016',
 '0038': 'Flt38 3 Sept 2017',
 '0048': 'Flt48 17 Aug 2018',
 '0019': 'Flt19 9 Sept 2016',
 '0051': 'Flt51 28 Aug 2018',
 '0059': 'Flt59 20 Aug 2019'}